# Generated by Django 4.2.7 on 2025-04-05 06:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код (напр. rector)')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_tr', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на файл')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт')),
                ('contact_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт')),
                ('contact_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт')),
                ('contact_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт')),
                ('contact_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт')),
                ('contact_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт')),
                ('responsibilities', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обязанности, Требования, Условия')),
                ('responsibilities_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обязанности, Требования, Условия')),
                ('responsibilities_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обязанности, Требования, Условия')),
                ('responsibilities_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обязанности, Требования, Условия')),
                ('responsibilities_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обязанности, Требования, Условия')),
                ('responsibilities_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Обязанности, Требования, Условия')),
                ('date_publication', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата публикации')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.leadershiptype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Руководство / Отделы / Вакансии',
            },
        ),
    ]
