# Generated by Django 4.2.7 on 2025-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='position',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Должность'),
        ),
    ]
