# Generated by Django 4.2.7 on 2025-04-18 11:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_leadership_position_leadership_position_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadership',
            name='description',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='link',
        ),
        migrations.CreateModel(
            name='LeadershipObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Сыллка')),
                ('leadership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.leadership', verbose_name='Тип')),
            ],
        ),
    ]
