# Generated by Django 4.2.7 on 2025-04-05 06:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(blank=True, help_text='Используется для группировки и отображения', max_length=100, null=True, verbose_name='Ключ страницы (пример: about, history, mission)')),
                ('page_key_ru', models.CharField(blank=True, help_text='Используется для группировки и отображения', max_length=100, null=True, verbose_name='Ключ страницы (пример: about, history, mission)')),
                ('page_key_ky', models.CharField(blank=True, help_text='Используется для группировки и отображения', max_length=100, null=True, verbose_name='Ключ страницы (пример: about, history, mission)')),
                ('page_key_tr', models.CharField(blank=True, help_text='Используется для группировки и отображения', max_length=100, null=True, verbose_name='Ключ страницы (пример: about, history, mission)')),
                ('page_key_ar', models.CharField(blank=True, help_text='Используется для группировки и отображения', max_length=100, null=True, verbose_name='Ключ страницы (пример: about, history, mission)')),
                ('page_key_en', models.CharField(blank=True, help_text='Используется для группировки и отображения', max_length=100, null=True, verbose_name='Ключ страницы (пример: about, history, mission)')),
                ('title_main', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главная Заголовка')),
                ('title_main_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главная Заголовка')),
                ('title_main_ky', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главная Заголовка')),
                ('title_main_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главная Заголовка')),
                ('title_main_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главная Заголовка')),
                ('title_main_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Главная Заголовка')),
                ('title2', models.CharField(blank=True, max_length=155, null=True, verbose_name='Под Заголовка')),
                ('title2_ru', models.CharField(blank=True, max_length=155, null=True, verbose_name='Под Заголовка')),
                ('title2_ky', models.CharField(blank=True, max_length=155, null=True, verbose_name='Под Заголовка')),
                ('title2_tr', models.CharField(blank=True, max_length=155, null=True, verbose_name='Под Заголовка')),
                ('title2_ar', models.CharField(blank=True, max_length=155, null=True, verbose_name='Под Заголовка')),
                ('title2_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Под Заголовка')),
                ('title_page', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Страницы')),
                ('title_page_ru', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Страницы')),
                ('title_page_ky', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Страницы')),
                ('title_page_tr', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Страницы')),
                ('title_page_ar', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Страницы')),
                ('title_page_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Страницы')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Данные о Страницы')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Данные о Страницы')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Данные о Страницы')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Данные о Страницы')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Данные о Страницы')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Данные о Страницы')),
                ('addresses', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресы, телефон номер, режим работы')),
                ('addresses_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресы, телефон номер, режим работы')),
                ('addresses_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресы, телефон номер, режим работы')),
                ('addresses_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресы, телефон номер, режим работы')),
                ('addresses_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресы, телефон номер, режим работы')),
                ('addresses_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Адресы, телефон номер, режим работы')),
                ('links_carta', models.URLField(blank=True, null=True, verbose_name='Ссылка на карту')),
                ('title_pdf', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_ru', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_ky', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_tr', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_ar', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('url_pdf', models.URLField(blank=True, null=True, verbose_name='Ссылка на Файл')),
                ('dowl_url', models.FileField(blank=True, null=True, upload_to='', verbose_name='PDF-Файл')),
            ],
            options={
                'verbose_name': 'Об Академий',
                'verbose_name_plural': 'Об Академий',
            },
        ),
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about-academy/', verbose_name='Фото')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AboutAcademy.about')),
            ],
            options={
                'verbose_name': 'Изображение для страницая',
                'verbose_name_plural': 'Изображение для страницая',
            },
        ),
    ]
