# Generated by Django 4.2.7 on 2025-04-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='about',
            name='addresses_ar',
        ),
        migrations.RemoveField(
            model_name='about',
            name='addresses_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='addresses_ky',
        ),
        migrations.RemoveField(
            model_name='about',
            name='addresses_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='addresses_tr',
        ),
        migrations.AddField(
            model_name='about',
            name='adres',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='about',
            name='number',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='about',
            name='rab',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Режим работы'),
        ),
    ]
