# Generated by Django 4.2.7 on 2025-04-19 09:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AboutAcademy', '0002_remove_about_addresses_remove_about_addresses_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='dowl_url',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_pdf',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_pdf_ar',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_pdf_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_pdf_ky',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_pdf_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_pdf_tr',
        ),
        migrations.RemoveField(
            model_name='about',
            name='url_pdf',
        ),
        migrations.AlterField(
            model_name='about',
            name='links_carta',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about-academy/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='AboutObjectPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_tr', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ar', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_pdf', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_ru', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_ky', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_tr', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_ar', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('title_pdf_en', models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Файла')),
                ('url_pdf', models.URLField(blank=True, null=True, verbose_name='Ссылка на Файл')),
                ('dowl_url', models.FileField(blank=True, null=True, upload_to='', verbose_name='PDF-Файл')),
                ('about_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_object_pdf', to='AboutAcademy.about', verbose_name='Обекты Об Академии')),
            ],
        ),
        migrations.CreateModel(
            name='AboutObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_tr', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ar', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('about_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_object', to='AboutAcademy.about', verbose_name='Второй обект об академии')),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='image_deteil', to='AboutAcademy.aboutimage')),
            ],
        ),
    ]
