# Generated by Django 4.2.7 on 2025-04-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта'),
        ),
        migrations.AddField(
            model_name='photos',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта'),
        ),
        migrations.AddField(
            model_name='photos',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта'),
        ),
        migrations.AddField(
            model_name='photos',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта'),
        ),
        migrations.AddField(
            model_name='photos',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта'),
        ),
        migrations.AddField(
            model_name='photos',
            name='title_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок сайта'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='date',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
