# Generated by Django 4.2.7 on 2025-04-23 11:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_obj',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_obj_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_obj_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_obj_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_obj_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description_obj_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_obj',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_obj_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_obj_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_obj_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_obj_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_obj_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка'),
        ),
    ]
