# Generated by Django 4.2.7 on 2025-04-05 06:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Тип информации')),
                ('title_ru', models.CharField(blank=True, max_length=225, null=True, verbose_name='Тип информации')),
                ('title_ky', models.CharField(blank=True, max_length=225, null=True, verbose_name='Тип информации')),
                ('title_tr', models.CharField(blank=True, max_length=225, null=True, verbose_name='Тип информации')),
                ('title_ar', models.CharField(blank=True, max_length=225, null=True, verbose_name='Тип информации')),
                ('title_en', models.CharField(blank=True, max_length=225, null=True, verbose_name='Тип информации')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('students_full_name', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное имя студента')),
                ('students_full_name_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное имя студента')),
                ('students_full_name_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное имя студента')),
                ('students_full_name_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное имя студента')),
                ('students_full_name_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное имя студента')),
                ('students_full_name_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное имя студента')),
                ('number', models.CharField(blank=True, max_length=225, null=True, verbose_name='Номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='ScientificJournalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students', verbose_name='Image')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.scientificjournal', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Обекты Студента',
                'verbose_name_plural': 'Объекты Студентов',
            },
        ),
    ]
