# Generated by Django 4.2.7 on 2025-04-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificjournal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='link',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='number',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='students_full_name',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='students_full_name_ar',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='students_full_name_en',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='students_full_name_ky',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='students_full_name_ru',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='students_full_name_tr',
        ),
        migrations.CreateModel(
            name='ScientificJournalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название работы')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название работы')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название работы')),
                ('name_tr', models.CharField(max_length=255, null=True, verbose_name='Название работы')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Название работы')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название работы')),
                ('description', models.TextField(verbose_name='Описание работы')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание работы')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание работы')),
                ('description_tr', models.TextField(null=True, verbose_name='Описание работы')),
                ('description_ar', models.TextField(null=True, verbose_name='Описание работы')),
                ('description_en', models.TextField(null=True, verbose_name='Описание работы')),
                ('img', models.ImageField(upload_to='work/', verbose_name='Изображение работы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='students.scientificjournal', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Работа студента',
                'verbose_name_plural': 'Работы студентов',
            },
        ),
    ]
