# Generated by Django 4.2.7 on 2025-04-15 09:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_scientificjournal_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='description',
            field=models.TextField(verbose_name='Описание сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Описание сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Описание сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='img',
            field=models.ImageField(upload_to='work/', verbose_name='Изображение сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='scientificjournalwork',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='детально')),
                ('detail_ru', ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='детально')),
                ('detail_ky', ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='детально')),
                ('detail_tr', ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='детально')),
                ('detail_ar', ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='детально')),
                ('detail_en', ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='детально')),
                ('img', models.ImageField(blank=True, null=True, upload_to='studentns')),
                ('dels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.scientificjournal', verbose_name='Детально')),
            ],
            options={
                'verbose_name': 'Детально',
                'verbose_name_plural': 'Детально',
            },
        ),
        migrations.AddField(
            model_name='scientificjournalwork',
            name='detail',
            field=models.ManyToManyField(blank=True, related_name='work_details', to='students.detail'),
        ),
    ]
