# Generated by Django 4.2.7 on 2025-04-17 17:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_scientificjournalwork_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificjournal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='scientificjournal',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='scientificjournalobject',
            name='image',
        ),
        migrations.AddField(
            model_name='scientificjournalobject',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='scientificjournalobject',
            name='description_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='scientificjournalobject',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='scientificjournalobject',
            name='description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='scientificjournalobject',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='scientificjournalobject',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='ScientificJournalObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Изображения')),
                ('cloj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.scientificjournal')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Избражения',
            },
        ),
        migrations.AddField(
            model_name='scientificjournalobject',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='image_deteil', to='students.scientificjournalobjectimage'),
        ),
    ]
