# Generated by Django 4.2.7 on 2025-04-19 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_scientificjournal_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='детально'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='детально'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='детально'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='детально'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='детально'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='detail_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='детально'),
        ),
    ]
