# Generated by Django 4.2.7 on 2025-04-05 06:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок объекта')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок объекта')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок объекта')),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок объекта')),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок объекта')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок объекта')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
                ('link_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
                ('link_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
                ('link_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
                ('link_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
                ('link_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
        migrations.CreateModel(
            name='AllEducationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_speciality_education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название специальности')),
                ('name_speciality_education_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название специальности')),
                ('name_speciality_education_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название специальности')),
                ('name_speciality_education_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название специальности')),
                ('name_speciality_education_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название специальности')),
                ('name_speciality_education_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название специальности')),
                ('status_education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус обучения')),
                ('status_education_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус обучения')),
                ('status_education_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус обучения')),
                ('status_education_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус обучения')),
                ('status_education_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус обучения')),
                ('status_education_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус обучения')),
                ('form_education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения')),
                ('form_education_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения')),
                ('form_education_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения')),
                ('form_education_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения')),
                ('form_education_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения')),
                ('form_education_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения')),
                ('perioud_education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Период обучения')),
                ('perioud_education_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Период обучения')),
                ('perioud_education_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Период обучения')),
                ('perioud_education_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Период обучения')),
                ('perioud_education_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Период обучения')),
                ('perioud_education_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Период обучения')),
                ('educations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.alleducation', verbose_name='Объекты Образования')),
            ],
        ),
    ]
