# Generated by Django 4.2.7 on 2025-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alleducation',
            name='link_ar',
        ),
        migrations.RemoveField(
            model_name='alleducation',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='alleducation',
            name='link_ky',
        ),
        migrations.RemoveField(
            model_name='alleducation',
            name='link_ru',
        ),
        migrations.RemoveField(
            model_name='alleducation',
            name='link_tr',
        ),
        migrations.AddField(
            model_name='alleducation',
            name='title2',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='alleducation',
            name='title2_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='alleducation',
            name='title2_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='alleducation',
            name='title2_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='alleducation',
            name='title2_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='alleducation',
            name='title2_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Второй заголовок'),
        ),
    ]
