# Generated by Django 4.2.7 on 2025-04-17 17:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='date_header',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='date_header_ar',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='date_header_en',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='date_header_ky',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='date_header_ru',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='date_header_tr',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_banner_ar',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_banner_en',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_banner_ky',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_banner_ru',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_banner_tr',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_obj_ar',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_obj_en',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_obj_ky',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_obj_ru',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image_obj_tr',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone_header_ar',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone_header_en',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone_header_ky',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone_header_ru',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone_header_tr',
        ),
        migrations.AddField(
            model_name='settings',
            name='date_headers',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='settings',
            name='date_headers_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='settings',
            name='date_headers_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='settings',
            name='date_headers_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='settings',
            name='date_headers_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='settings',
            name='date_headers_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип для сыллки'),
        ),
        migrations.AddField(
            model_name='settings',
            name='text_link',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Текст для сыллки'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_1',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок первый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_1_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок первый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_1_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок первый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_1_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок первый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_1_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок первый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_1_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок первый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_2',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок второй'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_2_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок второй'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_2_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок второй'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_2_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок второй'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_2_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок второй'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_2_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок второй'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_3',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок третий'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_3_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок третий'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_3_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок третий'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_3_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок третий'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_3_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок третий'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_3_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок третий'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_4',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок чётвёртый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_4_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок чётвёртый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_4_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок чётвёртый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_4_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок чётвёртый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_4_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок чётвёртый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_4_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок чётвёртый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_5',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок пятый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_5_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок пятый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_5_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок пятый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_5_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок пятый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_5_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок пятый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_5_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок пятый'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_6',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок шестой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_6_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок шестой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_6_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок шестой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_6_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок шестой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_6_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок шестой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_6_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок шестой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_7',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок седьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_7_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок седьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_7_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок седьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_7_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок седьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_7_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок седьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_7_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок седьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_8',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок восьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_8_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок восьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_8_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок восьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_8_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок восьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_8_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок восьмой'),
        ),
        migrations.AddField(
            model_name='settings',
            name='title_8_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок восьмой'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_banner',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_banner_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_banner_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_banner_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_banner_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_banner_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_obj',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_obj_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_obj_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_obj_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_obj_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description_obj_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email_footer',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Почта на футоре'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='face_book',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Фейсбук'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_above',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Изображение вверху'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='Фото Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_below',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Изображение снизу'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_obj',
            field=models.ImageField(blank=True, null=True, upload_to='settings/obj', verbose_name='Фото Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='insta_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Инстаграм'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Сыллка в главной'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location_ar',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location_en',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location_ky',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location_ru',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='location_tr',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='obj_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='obj_date_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='obj_date_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='obj_date_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='obj_date_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='obj_date_tr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone_header',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Номер телефона в Хедере'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_additional_professional_education',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка дополнительная профессиональная образования'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_additional_professional_education_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка дополнительная профессиональная образования'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_additional_professional_education_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка дополнительная профессиональная образования'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_additional_professional_education_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка дополнительная профессиональная образования'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_additional_professional_education_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка дополнительная профессиональная образования'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_additional_professional_education_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка дополнительная профессиональная образования'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_banner',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_banner_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_banner_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_banner_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_banner_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_banner_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Баннера'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_courses',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Курсов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_courses_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Курсов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_courses_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Курсов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_courses_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Курсов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_courses_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Курсов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_courses_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Курсов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_gallery',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Галлерий'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_gallery_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Галлерий'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_gallery_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Галлерий'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_gallery_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Галлерий'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_gallery_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Галлерий'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_gallery_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Галлерий'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journal_of_the_islamic_academy',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журнал исламской академии'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journal_of_the_islamic_academy_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журнал исламской академии'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journal_of_the_islamic_academy_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журнал исламской академии'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journal_of_the_islamic_academy_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журнал исламской академии'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journal_of_the_islamic_academy_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журнал исламской академии'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journal_of_the_islamic_academy_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журнал исламской академии'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journals_of_partner_universities',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журналы партнерских вузов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journals_of_partner_universities_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журналы партнерских вузов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journals_of_partner_universities_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журналы партнерских вузов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journals_of_partner_universities_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журналы партнерских вузов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journals_of_partner_universities_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журналы партнерских вузов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_journals_of_partner_universities_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка журналы партнерских вузов'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_news',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_news_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_news_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_news_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_news_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_news_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Новости'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_obj',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_obj_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_obj_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_obj_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_obj_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_obj_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Объекта Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_scientific_degrees',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка научные степени'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_scientific_degrees_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка научные степени'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_scientific_degrees_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка научные степени'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_scientific_degrees_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка научные степени'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_scientific_degrees_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка научные степени'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_scientific_degrees_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка научные степени'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_we_suggest_you_watch_it',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_we_suggest_you_watch_it_ar',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_we_suggest_you_watch_it_en',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_we_suggest_you_watch_it_ky',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_we_suggest_you_watch_it_ru',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Предлогаем к просмотру'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title_we_suggest_you_watch_it_tr',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовка Предлогаем к просмотру'),
        ),
    ]
