# Generated by Django 4.2.7 on 2025-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_settings_date_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='date_muslim',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Дата мусульманская'),
        ),
    ]
