# Generated by Django 4.2.7 on 2025-04-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_settings_date_muslim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='link',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='text_link',
        ),
        migrations.CreateModel(
            name='SettingsObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Сыллка в главной')),
                ('text_link', models.CharField(blank=True, max_length=225, null=True, verbose_name='Текст для сыллки')),
                ('text_link_ru', models.CharField(blank=True, max_length=225, null=True, verbose_name='Текст для сыллки')),
                ('text_link_ky', models.CharField(blank=True, max_length=225, null=True, verbose_name='Текст для сыллки')),
                ('text_link_tr', models.CharField(blank=True, max_length=225, null=True, verbose_name='Текст для сыллки')),
                ('text_link_ar', models.CharField(blank=True, max_length=225, null=True, verbose_name='Текст для сыллки')),
                ('text_link_en', models.CharField(blank=True, max_length=225, null=True, verbose_name='Текст для сыллки')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип для сыллки')),
                ('settings_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_objects', to='mainpage.settings', verbose_name='Настройки')),
            ],
        ),
    ]
