# Generated by Django 4.2.7 on 2025-04-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_remove_settings_link_remove_settings_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscard',
            options={'verbose_name': 'Карта новостей', 'verbose_name_plural': 'Карты новостей'},
        ),
    ]
