# Generated by Django 4.2.7 on 2025-04-07 05:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ology', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='description_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='description_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Сыллка'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='number',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Общество'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='title_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Общество'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='title_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Общество'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='title_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Общество'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='title_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Общество'),
        ),
        migrations.AlterField(
            model_name='ology',
            name='title_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Общество'),
        ),
    ]
