# Generated by Django 4.2.7 on 2025-04-15 09:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ology', '0002_ology_image_alter_ology_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ology',
            options={'verbose_name': 'Наука', 'verbose_name_plural': 'Науки'},
        ),
        migrations.RemoveField(
            model_name='ology',
            name='image',
        ),
        migrations.AlterField(
            model_name='ology',
            name='link',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Сыллка'),
        ),
        migrations.CreateModel(
            name='OlogyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_tr', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_ar', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Сыллка')),
                ('ology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ology.ology', verbose_name='Обект образавания')),
            ],
        ),
    ]
