# Generated by Django 4.2.7 on 2025-04-17 17:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ology', '0003_alter_ology_options_remove_ology_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ology',
            name='description_glub',
            field=ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='Описание главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='description_glub_ar',
            field=ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='Описание главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='description_glub_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='Описание главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='description_glub_ky',
            field=ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='Описание главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='description_glub_ru',
            field=ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='Описание главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='description_glub_tr',
            field=ckeditor.fields.RichTextField(blank=True, max_length=225, null=True, verbose_name='Описание главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='title_glub',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='title_glub_ar',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='title_glub_en',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='title_glub_ky',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='title_glub_ru',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок главный'),
        ),
        migrations.AddField(
            model_name='ology',
            name='title_glub_tr',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Заголовок главный'),
        ),
    ]
