# Generated by Django 4.2.7 on 2025-04-05 06:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Поступить в академию')),
                ('title_ru', models.CharField(blank=True, max_length=225, null=True, verbose_name='Поступить в академию')),
                ('title_ky', models.CharField(blank=True, max_length=225, null=True, verbose_name='Поступить в академию')),
                ('title_tr', models.CharField(blank=True, max_length=225, null=True, verbose_name='Поступить в академию')),
                ('title_ar', models.CharField(blank=True, max_length=225, null=True, verbose_name='Поступить в академию')),
                ('title_en', models.CharField(blank=True, max_length=225, null=True, verbose_name='Поступить в академию')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Абитуриентам',
                'verbose_name_plural': 'Абитуриентам',
            },
        ),
    ]
